export const chatTypes = {
  LIST_REQUESTED: 'LIST_CHAT_REQUESTED',
  LIST_SUCCEEDED: 'LIST_CHAT_SUCCEEDED',
  LIST_FAILED: 'LIST_CHAT_FAILED',

  CREATE_CHAT_REQUESTED: 'CREATE_CHAT_REQUESTED',
  CREATE_CHAT_SUCCEEDED: 'CREATE_CHAT_SUCCEEDED',
  CREATE_CHAT_FAILED: 'CREATE_CHAT_FAILED',

  UPDATE_REQUESTED: 'UPDATE_CHAT_REQUESTED',
  UPDATE_SUCCEEDED: 'UPDATE_CHAT_SUCCEEDED',
  UPDATE_FAILED: 'UPDATE_CHAT_FAILED',

  DELETE_CHAT_REQUESTED: 'DELETE_CHAT_REQUESTED',
  DELETE_CHAT_SUCCEEDED: 'DELETE_CHAT_SUCCEEDED',
  DELETE_CHAT_FAILED: 'DELETE_CHAT_FAILED',

  CLEAR: 'CLEAR_CHAT'
}