export const petTypes = {
  REGISTER_REQUESTED: 'REGISTER_PETS_REQUESTED',
  REGISTER_SUCCEEDED: 'REGISTER_PETS_SUCCEEDED',
  REGISTER_FAILED: 'REGISTER_PETS_FAILED',
  LIST_REQUESTED: 'LIST_PETS_REQUESTED',
  LIST_SUCCEEDED: 'LIST_PETS_SUCCEEDED',
  LIST_FAILED: 'LIST_PETS_FAILED',
  LOAD_REQUESTED: 'LOAD_PET_REQUESTED',
  LOAD_SUCCEEDED: 'LOAD_PET_SUCCEEDED',
  LOAD_FAILED: 'LOAD_PET_FAILED',
  ADOPT_REQUESTED: 'ADOPT_PET_REQUESTED',
  ADOPT_SUCCEEDED: 'ADOPT_PET_SUCCEEDED',
  ADOPT_FAILED: 'ADOPT_PET_FAILED',
  CLEAR: 'CLEAR_PETS'
}
