export const profileTypes = {
  CREATE_REQUESTED: 'CREATE_USER_REQUESTED',
  CREATE_SUCCEEDED: 'CREATE_USER_SUCCEEDED',
  CREATE_FAILED: 'CREATE_USER_FAILED',
  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOAD_REQUESTED: 'LOAD_USER_REQUESTED',
  LOAD_SUCCEEDED: 'LOAD_USER_SUCCEEDED',
  LOAD_FAILED: 'LOAD_USER_FAILED',
  LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
  LOGOUT_SUCCEEDED: 'LOGOUT_SUCCEEDED',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  CLEAR: 'CLEAR_USER'
}
